"""updated table relationships

Revision ID: 9dbba71115d4
Revises: c07af3a7634b
Create Date: 2025-06-06 17:53:08.759832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dbba71115d4'
down_revision: Union[str, None] = 'c07af3a7634b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('articles_author_id_fkey', 'articles', type_='foreignkey')
    op.create_foreign_key(None, 'articles', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.add_column('projects', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'is_published')
    op.drop_column('projects', 'is_featured')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key('articles_author_id_fkey', 'articles', 'users', ['author_id'], ['id'])
    op.alter_column('articles', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
