"""change for skills

Revision ID: c07af3a7634b
Revises: 9058c368bf32
Create Date: 2025-06-06 17:40:04.965290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c07af3a7634b'
down_revision: Union[str, None] = '9058c368bf32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('proficiency_level', sa.Float(), nullable=False),
    sa.Column('years_experience', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_highlighted', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id', name='unique_user_skill')
    )
    op.create_index(op.f('ix_skill_users_id'), 'skill_users', ['id'], unique=False)
    op.add_column('projects', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('skills', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'skills', ['name'])
    op.drop_column('skills', 'proficiency_level')
    op.drop_column('skills', 'updated_at')
    op.drop_column('skills', 'created_at')
    op.drop_column('skills', 'order')
    op.drop_column('skills', 'years_experience')
    op.drop_column('skills', 'is_highlighted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('is_highlighted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('skills', sa.Column('years_experience', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('skills', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('skills', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('skills', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('skills', sa.Column('proficiency_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'skills', type_='unique')
    op.drop_column('skills', 'is_active')
    op.drop_column('projects', 'user_id')
    op.drop_index(op.f('ix_skill_users_id'), table_name='skill_users')
    op.drop_table('skill_users')
    # ### end Alembic commands ###
